### PR TITLE
Fix gen_server_opts not being passed to GenServer

### LINKED ISSUE #172: Client does not accept name as an option
Currently it is not possible to do
`Client.start_link("localhost", 33722, [name: __MODULE__])`

### PR DESCRIPTION
**Pull request by thecodeboss**
In the docs, the `gen_server_opts` option was listed, but not actually hooked up to pass the opts to the `GenServer` handlers.
This fixes #172, and the tests I added verify that.

### CODE REVIEW

File: lib/thrift/binary/framed/client.ex [hunk 1]
```diff
@@ -81,14 +81,15 @@ defmodule Thrift.Binary.Framed.Client do
 
      - `send_timeout`: An integer that governs how long our connection waits when sending data.
 
-    `gen_server_opts`: A keyword list of options that control the gen_server behaviour.
+     - `gen_server_opts`: A keyword list of options that control the gen_server behaviour.
```
Comment (fishcakez) [inline lib/thrift/binary/framed/client.ex]: I think this might be easier to use with the GenServer options as top level. For tcp the list is not a `Keyword.t` so we can't have those options at the top level, and must nest them. For GenServer start I think we could support `:name`, `:spawn_opt` and `:debug`. The other one is`:timeout` and that is not helpful to us because we don't do anything in `init/1` so never block, and then we don't need to worry about a key clash.

Also these options have different meaning to when `:gen_server_opts` is used elsewhere, which is confusing, and breaks the abstraction I think.

File: lib/thrift/binary/framed/client.ex [hunk 2]
```diff
@@ -81,14 +81,15 @@ defmodule Thrift.Binary.Framed.Client do
...
 
      - `timeout`:  The amount of time to wait (in milliseconds) for a reply from a `GenServer` call.
 
   """
   @spec start_link(String.t, (0..65_535), options) :: GenServer.on_start
```
Comment (fishcakez) [inline lib/thrift/binary/framed/client.ex]: While we do this change could we switch from `options` to `[option]`. It is no possible to compose a list type, but an element type can be composed with `[option | other_option_type]`.

File: lib/thrift/binary/framed/client.ex (hunk 1 above)
Comment (thecodeboss) [reply lib/thrift/binary/framed/client.ex]: By top level, do you mean being able to specify the options like
```elixir
Client.start_link("localhost", 8080, name: __MODULE__)
```
instead of
```elixir
Client.start_link("localhost", 8080, gen_server_opts: [name: __MODULE__])
```
Also I've noticed that I misinterpreted that line to have a missing `-`, when actually it was intentionally unindented as a separate list of options from `tcp_opts`.

Comment (fishcakez) [reply lib/thrift/binary/framed/client.ex]: I did mean that yes but didn't notice this was just `-`. Lets go with this change :).

**Comment by thecodeboss** [comment]
Made changes to how the options are passed based on the feedback, so they are now top-level. I think this makes the client a bit simpler to use when specifying options.
